nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:4200']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
